vich_uploader:
    db_driver: orm

    mappings: 
        espace_image:
            uri_prefix: /images/EspaceDeCoworkings
            upload_destination: '%kernel.project_dir%/public/images/EspaceDeCoworkings'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
